# Generated by Django 3.2.4 on 2022-02-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=150)),
                ('Password', models.CharField(max_length=400)),
                ('Email', models.CharField(max_length=150)),
                ('Salt', models.CharField(default='', max_length=400)),
            ],
        ),
    ]
