# Generated by Django 3.2.4 on 2022-02-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Picture',
            field=models.ImageField(default='', upload_to='pictures'),
        ),
    ]
